import { useCallback, useEffect, useRef, useState } from 'react';
import { Platform } from 'react-native';
import { MAP_STYLE_URL } from '@/hooks/useOfflineMapPack';
import { REGIONS, type Region } from '@/constants/regions';

// MAPS.ME-style per-region detail packs, one per aimag (+ Ulaanbaatar).
//
// The country overview pack (useOfflineMapPack.ts) stops at z11 because
// the whole country at z14 is ~1.5M tile requests — but dirt tracks, the
// roads that actually matter off the asphalt, only exist in the tiles from
// z13 up. So detail is downloaded per region, z12–13 only (the overview
// already covers everything below; z14 would triple the request count for
// the same tracks), for the aimags the traveller is going to. Bounds come
// from the OSM admin_level=4 boundaries (constants/regions.ts, generated by
// TMB/scripts/osm/), so a pack covers the real aimag shape's bbox, not a
// hand-drawn rectangle.

const REGION_MIN_ZOOM = 12;
const REGION_MAX_ZOOM = 13;
const PACK_PREFIX = 'mongolia-region-v1:';

export type RegionPackStatus = 'none' | 'downloading' | 'complete' | 'error';

export interface RegionPackState {
  status: RegionPackStatus;
  progress: number; // 0-100
}

export function useOfflineRegionPacks() {
  const [states, setStates] = useState<Record<string, RegionPackState>>({});
  const packIds = useRef<Record<string, string>>({});
  const [ready, setReady] = useState(false);

  const setRegion = useCallback((id: string, patch: Partial<RegionPackState>) => {
    setStates(prev => {
      const base: RegionPackState = prev[id] ?? { status: 'none', progress: 0 };
      return { ...prev, [id]: { ...base, ...patch } };
    });
  }, []);

  useEffect(() => {
    if (Platform.OS === 'web') return;
    const { OfflineManager } = require('@maplibre/maplibre-react-native');
    let cancelled = false;
    OfflineManager.getPacks().then((packs: any[]) => {
      if (cancelled) return;
      const next: Record<string, RegionPackState> = {};
      for (const p of packs) {
        const name: string | undefined = p.metadata?.name;
        if (!name?.startsWith(PACK_PREFIX)) continue;
        const id = name.slice(PACK_PREFIX.length);
        packIds.current[id] = p.id;
        next[id] = { status: 'complete', progress: 100 };
      }
      setStates(next);
      setReady(true);
    }).catch(() => setReady(true));
    return () => { cancelled = true; };
  }, []);

  const download = useCallback(async (region: Region) => {
    if (Platform.OS === 'web') return;
    if (states[region.id]?.status === 'downloading') return;
    const { OfflineManager } = require('@maplibre/maplibre-react-native');
    setRegion(region.id, { status: 'downloading', progress: 0 });
    try {
      const pack = await OfflineManager.createPack(
        {
          mapStyle: MAP_STYLE_URL,
          bounds: region.bbox,
          minZoom: REGION_MIN_ZOOM,
          maxZoom: REGION_MAX_ZOOM,
          metadata: { name: PACK_PREFIX + region.id },
        },
        (_pack: any, status: any) => {
          setRegion(region.id, { progress: Math.round(status.percentage ?? 0) });
          if (status.state === 'complete') setRegion(region.id, { status: 'complete', progress: 100 });
        },
        () => setRegion(region.id, { status: 'error' }),
      );
      packIds.current[region.id] = pack.id;
    } catch {
      setRegion(region.id, { status: 'error' });
    }
  }, [states, setRegion]);

  const remove = useCallback(async (region: Region) => {
    if (Platform.OS === 'web') return;
    const { OfflineManager } = require('@maplibre/maplibre-react-native');
    const id = packIds.current[region.id];
    if (id) await OfflineManager.deletePack(id).catch(() => {});
    delete packIds.current[region.id];
    setRegion(region.id, { status: 'none', progress: 0 });
  }, [setRegion]);

  const stateOf = useCallback((region: Region): RegionPackState => states[region.id] ?? { status: 'none', progress: 0 }, [states]);

  return { ready, regions: REGIONS, stateOf, download, remove };
}
